server:
  port: 8080

spring:
  application:
    name: inventory-dashboard
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_dashboard
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# CORS Configuration
cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# ML Script Configuration
ml:
  script-path: "../ml/forecast.py"
  python-command: "python3"

# Logging Configuration
logging:
  level:
    com.inventory: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 